# Use Node 20+ (or 22+) which has good support for modern ES modules
FROM node:22

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Bundle app source
COPY . .

# Expose the port
EXPOSE 10000

# Start the server
CMD [ "node", "server.js" ]
